// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
	UserId int64 `json:"user_id"`
}

type Response struct {
	Message string `form:"message"`
}
